apiVersion: apps/v1
kind: Deployment
metadata:
  name: rexelpay-onboarding-prod
  
spec:
  selector:
    matchLabels:
      app: rexelpay-onboarding-pod
  template:
    metadata:
      labels:
        app: rexelpay-onboarding-pod
    spec:
      containers:
      - name: rexelpay-onboarding-container
        image: rexelpay.azurecr.io/rexelpay-onboarding-prod:v1
        resources:
          limits:
            memory: "256Mi"
            cpu: "300m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: rexelpay-onboarding-service
spec:
  selector:
    app: rexelpay-onboarding-pod
  ports:
  - port: 8086
    targetPort: 80
  type: LoadBalancer
